# Configuration for Alacritty, the GPU enhanced terminal emulator.

schemes:
  latte: &latte # Default colors
    primary:
      background: "#EFF1F5" # base
      foreground: "#4C4F69" # text
      # Bright and dim foreground colors
      dim_foreground: "#4C4F69" # text
      bright_foreground: "#4C4F69" # text

    # Cursor colors
    cursor:
      text: "#EFF1F5" # base
      cursor: "#DC8A78" # rosewater
    vi_mode_cursor:
      text: "#EFF1F5" # base
      cursor: "#7287FD" # lavender

    # Search colors
    search:
      matches:
        foreground: "#EFF1F5" # base
        background: "#6C6F85" # subtext0
      focused_match:
        foreground: "#EFF1F5" # base
        background: "#40A02B" # green
      footer_bar:
        foreground: "#EFF1F5" # base
        background: "#6C6F85" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#EFF1F5" # base
        background: "#DF8E1D" # yellow
      end:
        foreground: "#EFF1F5" # base
        background: "#6C6F85" # subtext0

    # Selection colors
    selection:
      text: "#EFF1F5" # base
      background: "#DC8A78" # rosewater

    # Normal colors
    normal:
      black: "#5C5F77" # subtext1
      red: "#D20F39" # red
      green: "#40A02B" # green
      yellow: "#DF8E1D" # yellow
      blue: "#1E66F5" # blue
      magenta: "#EA76CB" # pink
      cyan: "#179299" # teal
      white: "#ACB0BE" # surface2

    # Bright colors
    bright:
      black: "#6C6F85" # subtext0
      red: "#D20F39" # red
      green: "#40A02B" # green
      yellow: "#DF8E1D" # yellow
      blue: "#1E66F5" # blue
      magenta: "#EA76CB" # pink
      cyan: "#179299" # teal
      white: "#BCC0CC" # surface1

    # Dim colors
    dim:
      black: "#5C5F77" # subtext1
      red: "#D20F39" # red
      green: "#40A02B" # green
      yellow: "#DF8E1D" # yellow
      blue: "#1E66F5" # blue
      magenta: "#EA76CB" # pink
      cyan: "#179299" # teal
      white: "#ACB0BE" # surface2

    indexed_colors:
      - { index: 16, color: "#FE640B" }
      - { index: 17, color: "#DC8A78" }

  frappe: &frappe # Default colors
    primary:
      background: "#303446" # base
      foreground: "#C6D0F5" # text
      # Bright and dim foreground colors
      dim_foreground: "#C6D0F5" # text
      bright_foreground: "#C6D0F5" # text

    # Cursor colors
    cursor:
      text: "#303446" # base
      cursor: "#F2D5CF" # rosewater
    vi_mode_cursor:
      text: "#303446" # base
      cursor: "#BABBF1" # lavender

    # Search colors
    search:
      matches:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0
      focused_match:
        foreground: "#303446" # base
        background: "#A6D189" # green
      footer_bar:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#303446" # base
        background: "#E5C890" # yellow
      end:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0

    # Selection colors
    selection:
      text: "#303446" # base
      background: "#F2D5CF" # rosewater

    # Normal colors
    normal:
      black: "#51576D" # surface1
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#B5BFE2" # subtext1

    # Bright colors
    bright:
      black: "#626880" # surface2
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#A5ADCE" # subtext0

    # Dim colors
    dim:
      black: "#51576D" # surface1
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#B5BFE2" # subtext1

    indexed_colors:
      - { index: 16, color: "#EF9F76" }
      - { index: 17, color: "#F2D5CF" }

  macchiato: &macchiato # Default colors
    primary:
      background: "#24273A" # base
      foreground: "#CAD3F5" # text
      # Bright and dim foreground colors
      dim_foreground: "#CAD3F5" # text
      bright_foreground: "#CAD3F5" # text

    # Cursor colors
    cursor:
      text: "#24273A" # base
      cursor: "#F4DBD6" # rosewater
    vi_mode_cursor:
      text: "#24273A" # base
      cursor: "#B7BDF8" # lavender

    # Search colors
    search:
      matches:
        foreground: "#24273A" # base
        background: "#A5ADCB" # subtext0
      focused_match:
        foreground: "#24273A" # base
        background: "#A6DA95" # green
      footer_bar:
        foreground: "#24273A" # base
        background: "#A5ADCB" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#24273A" # base
        background: "#EED49F" # yellow
      end:
        foreground: "#24273A" # base
        background: "#A5ADCB" # subtext0

    # Selection colors
    selection:
      text: "#24273A" # base
      background: "#F4DBD6" # rosewater

    # Normal colors
    normal:
      black: "#494D64" # surface1
      red: "#ED8796" # red
      green: "#A6DA95" # green
      yellow: "#EED49F" # yellow
      blue: "#8AADF4" # blue
      magenta: "#F5BDE6" # pink
      cyan: "#8BD5CA" # teal
      white: "#B8C0E0" # subtext1

    # Bright colors
    bright:
      black: "#5B6078" # surface2
      red: "#ED8796" # red
      green: "#A6DA95" # green
      yellow: "#EED49F" # yellow
      blue: "#8AADF4" # blue
      magenta: "#F5BDE6" # pink
      cyan: "#8BD5CA" # teal
      white: "#A5ADCB" # subtext0

    # Dim colors
    dim:
      black: "#494D64" # surface1
      red: "#ED8796" # red
      green: "#A6DA95" # green
      yellow: "#EED49F" # yellow
      blue: "#8AADF4" # blue
      magenta: "#F5BDE6" # pink
      cyan: "#8BD5CA" # teal
      white: "#B8C0E0" # subtext1

    indexed_colors:
      - { index: 16, color: "#F5A97F" }
      - { index: 17, color: "#F4DBD6" }

  mocha: &mocha # Default colors
    primary:
      background: "#1E1E2E" # base
      foreground: "#CDD6F4" # text
      # Bright and dim foreground colors
      dim_foreground: "#CDD6F4" # text
      bright_foreground: "#CDD6F4" # text

    # Cursor colors
    cursor:
      text: "#1E1E2E" # base
      cursor: "#F5E0DC" # rosewater
    vi_mode_cursor:
      text: "#1E1E2E" # base
      cursor: "#B4BEFE" # lavender

    # Search colors
    search:
      matches:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0
      focused_match:
        foreground: "#1E1E2E" # base
        background: "#A6E3A1" # green
      footer_bar:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#1E1E2E" # base
        background: "#F9E2AF" # yellow
      end:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0

    # Selection colors
    selection:
      text: "#1E1E2E" # base
      background: "#F5E0DC" # rosewater

    # Normal colors
    normal:
      black: "#45475A" # surface1
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#BAC2DE" # subtext1

    # Bright colors
    bright:
      black: "#585B70" # surface2
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#A6ADC8" # subtext0

    # Dim colors
    dim:
      black: "#45475A" # surface1
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#BAC2DE" # subtext1

    indexed_colors:
      - { index: 16, color: "#FAB387" }
      - { index: 17, color: "#F5E0DC" }

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: "1.0"
#
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
# TERM: xterm-256color

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 2
    y: 2

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  decorations: full

  # When true, alacritty starts maximized.
  # startup_mode: Maximized

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number of lines the terminal
  # should scroll when the alternate screen buffer is active. This is used
  # to allow mouse scrolling for applications like `man`.
  #
  # Specifying `0` will disable faux scrolling.
  #faux_multiplier: 3

# Spaces per Tab (changes require restart)
#
# This setting defines the width of a tab in cells.
#
# Some applications, like Emacs, rely on knowing about the width of a tab.
# To prevent unexpected behavior in these applications, it's also required to
# change the `it` value in terminfo when altering this setting.
font:
  size: 15
  normal:
    family: Liga SFMono Nerd Font
  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0
  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  use_thin_strokes: true
# Colors (Solarized dark)
colors:
  indexed_colors:
    - { index: 16, color: "0xcb4b16" }
    - { index: 17, color: "0xd33682" }
    - { index: 18, color: "0x073642" }
    - { index: 19, color: "0x586e75" }
    - { index: 20, color: "0x839496" }
    - { index: 21, color: "0xeee8d5" }
  key_bindings:
    - { key: D, mods: Command, chars: "\x06\x76" }
    - { key: D, mods: Command|Shift, chars: "\x06\x73" }
    - { key: W, mods: Command, chars: "\x06\x78" }
    - { key: H, mods: Command, chars: "\x06\x68" }
    - { key: J, mods: Command, chars: "\x06\x6a" }
    - { key: K, mods: Command, chars: "\x06\x6b" }
    - { key: L, mods: Command, chars: "\x06\x6c" }
    - { key: T, mods: Command, chars: "\x06\x63" }
    - { key: Key1, mods: Command, chars: "\x06\x31" }
    - { key: Key2, mods: Command, chars: "\x06\x32" }
    - { key: Key3, mods: Command, chars: "\x06\x33" }
    - { key: Key4, mods: Command, chars: "\x06\x34" }
    - { key: Key5, mods: Command, chars: "\x06\x35" }
    - { key: Key6, mods: Command, chars: "\x06\x36" }
    - { key: Key7, mods: Command, chars: "\x06\x37" }
    - { key: Key8, mods: Command, chars: "\x06\x38" }
    - { key: Key9, mods: Command, chars: "\x06\x39" }
    - { key: Left, mods: Command, chars: "\x06\x48" }
    - { key: Down, mods: Command, chars: "\x06\x4a" }
    - { key: Up, mods: Command, chars: "\x06\x4b" }
    - { key: Right, mods: Command, chars: "\x06\x4c" }

colors: *frappe
