[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#11111b"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "BerkeleyMonoVariable2 Nerd Font Mono"

[font.bold_italic]
family = "BerkeleyMonoVariable2 Nerd Font Mono"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "BerkeleyMonoVariable2 Nerd Font Mono"

[font.normal]
family = "BerkeleyMonoVariable2 Nerd Font Mono"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u0001v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001s"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001w"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001L"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOR0"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOR1"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOR2"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOR3"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOR4"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOR5"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOR6"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOR7"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOR8"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "Copy"
mouse = "Left"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.98
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
