# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  TERM: xterm-256color
#
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
# TERM: xterm-256color

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 0
    y: 0
  opacity: 0.98
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  decorations: full
  option_as_alt: OnlyLeft

  # When true, alacritty starts maximized.
  # startup_mode: Maximized
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"
scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number of lines the terminal
  # should scroll when the alternate screen buffer is active. This is used
  # to allow mouse scrolling for applications like `man`.
  #
  # Specifying `0` will disable faux scrolling.
  #faux_multiplier: 3

# Spaces per Tab (changes require restart)
#
# This setting defines the width of a tab in cells.
#
# Some applications, like Emacs, rely on knowing about the width of a tab.
# To prevent unexpected behavior in these applications, it's also required to
# change the `it` value in terminfo when altering this setting.
font:
  size: 15
  normal:
    family: Liga SFMono Nerd Font
  bold:
    family: Liga SFMono Nerd Font
  italic:
    family: Liga SFMono Nerd Font
  bold_italic:
    family: Liga SFMono Nerd Font
  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true # When set to `true`, selected text will be copied to the primary clipboard.

cursor:
  style: Block
  unfocused_hollow: true # If this is `true`, the cursor will be rendered as a hollow box when the window is not focused.

mouse:
  hide_when_typing: true

mouse_bindings:
  - { mouse: Left, action: Copy }
  - { mouse: Middle, action: PasteSelection }
key_bindings:
  # https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/
  - { key: D, mods: Command, chars: "\x01\x76" }
  - { key: D, mods: Command|Shift, chars: "\x01\x73" }
  - { key: W, mods: Command, chars: "\x01\x78" }
  - { key: H, mods: Command, chars: "\x01\x68" }
  - { key: J, mods: Command, chars: "\x01\x6a" }
  - { key: K, mods: Command, chars: "\x01\x6b" }
  - { key: L, mods: Command, chars: "\x01\x6c" }
  - { key: T, mods: Command, chars: "\x01\x63" }
  - { key: Key1, mods: Command, chars: "\x01\x31" }
  - { key: Key2, mods: Command, chars: "\x01\x32" }
  - { key: Key3, mods: Command, chars: "\x01\x33" }
  - { key: Key4, mods: Command, chars: "\x01\x34" }
  - { key: Key5, mods: Command, chars: "\x01\x35" }
  - { key: Key6, mods: Command, chars: "\x01\x36" }
  - { key: Key7, mods: Command, chars: "\x01\x37" }
  - { key: Key8, mods: Command, chars: "\x01\x38" }
  - { key: Key9, mods: Command, chars: "\x01\x39" }
  - { key: Left, mods: Command, chars: "\x01\x48" }
  - { key: Down, mods: Command, chars: "\x01\x4a" }
  - { key: Up, mods: Command, chars: "\x01\x4b" }
  - { key: Right, mods: Command, chars: "\x01\x4c" }
  # go to tmux session by id
  - { key: Key1, mods: Alt, chars: "\x1b\x4f\x52\x30" }
  - { key: Key2, mods: Alt, chars: "\x1b\x4f\x52\x31" }
  - { key: Key3, mods: Alt, chars: "\x1b\x4f\x52\x32" }
  - { key: Key4, mods: Alt, chars: "\x1b\x4f\x52\x33" }
  - { key: Key5, mods: Alt, chars: "\x1b\x4f\x52\x34" }
  - { key: Key6, mods: Alt, chars: "\x1b\x4f\x52\x35" }
  - { key: Key7, mods: Alt, chars: "\x1b\x4f\x52\x36" }
  - { key: Key8, mods: Alt, chars: "\x1b\x4f\x52\x37" }
  - { key: Key9, mods: Alt, chars: "\x1b\x4f\x52\x38" }
  - { key: J, mods: Alt, chars: "\x1bj" }
  - { key: K, mods: Alt, chars: "\x1bk" }
  - { key: H, mods: Alt, chars: "\x1bh" }
  - { key: L, mods: Alt, chars: "\x1bl" }
schemes:
  frappe: &frappe # Default colors
    primary:
      background: "#303446" # base
      foreground: "#C6D0F5" # text
      # Bright and dim foreground colors
      dim_foreground: "#C6D0F5" # text
      bright_foreground: "#C6D0F5" # text

    # Cursor colors
    cursor:
      text: "#303446" # base
      cursor: "#F2D5CF" # rosewater
    vi_mode_cursor:
      text: "#303446" # base
      cursor: "#BABBF1" # lavender

    # Search colors
    search:
      matches:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0
      focused_match:
        foreground: "#303446" # base
        background: "#A6D189" # green
      footer_bar:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#303446" # base
        background: "#E5C890" # yellow
      end:
        foreground: "#303446" # base
        background: "#A5ADCE" # subtext0

    # Selection colors
    selection:
      text: "#303446" # base
      background: "#F2D5CF" # rosewater

    # Normal colors
    normal:
      black: "#51576D" # surface1
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#B5BFE2" # subtext1

    # Bright colors
    bright:
      black: "#626880" # surface2
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#A5ADCE" # subtext0

    # Dim colors
    dim:
      black: "#51576D" # surface1
      red: "#E78284" # red
      green: "#A6D189" # green
      yellow: "#E5C890" # yellow
      blue: "#8CAAEE" # blue
      magenta: "#F4B8E4" # pink
      cyan: "#81C8BE" # teal
      white: "#B5BFE2" # subtext1

    indexed_colors:
      - { index: 16, color: "#EF9F76" }
      - { index: 17, color: "#F2D5CF" }

  macchiato: &macchiato # Default colors
    primary:
      background: "#24273A" # base
      foreground: "#CAD3F5" # text
      # Bright and dim foreground colors
      dim_foreground: "#CAD3F5" # text
      bright_foreground: "#CAD3F5" # text

    # Cursor colors
    cursor:
      text: "#24273A" # base
      cursor: "#F4DBD6" # rosewater
    vi_mode_cursor:
      text: "#24273A" # base
      cursor: "#B7BDF8" # lavender

    # Search colors
    search:
      matches:
        foreground: "#24273A" # base
        background: "#A5ADCB" # subtext0
      focused_match:
        foreground: "#24273A" # base
        background: "#A6DA95" # green
      footer_bar:
        foreground: "#24273A" # base
        background: "#A5ADCB" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#24273A" # base
        background: "#EED49F" # yellow
      end:
        foreground: "#24273A" # base
        background: "#A5ADCB" # subtext0

    # Selection colors
    selection:
      text: "#24273A" # base
      background: "#F4DBD6" # rosewater

    # Normal colors
    normal:
      black: "#494D64" # surface1
      red: "#ED8796" # red
      green: "#A6DA95" # green
      yellow: "#EED49F" # yellow
      blue: "#8AADF4" # blue
      magenta: "#F5BDE6" # pink
      cyan: "#8BD5CA" # teal
      white: "#B8C0E0" # subtext1

    # Bright colors
    bright:
      black: "#5B6078" # surface2
      red: "#ED8796" # red
      green: "#A6DA95" # green
      yellow: "#EED49F" # yellow
      blue: "#8AADF4" # blue
      magenta: "#F5BDE6" # pink
      cyan: "#8BD5CA" # teal
      white: "#A5ADCB" # subtext0

    # Dim colors
    dim:
      black: "#494D64" # surface1
      red: "#ED8796" # red
      green: "#A6DA95" # green
      yellow: "#EED49F" # yellow
      blue: "#8AADF4" # blue
      magenta: "#F5BDE6" # pink
      cyan: "#8BD5CA" # teal
      white: "#B8C0E0" # subtext1

    indexed_colors:
      - { index: 16, color: "#F5A97F" }
      - { index: 17, color: "#F4DBD6" }

  mocha: &mocha # Default colors
    primary:
      background: "#11111b" # base
      foreground: "#CDD6F4" # text
      # Bright and dim foreground colors
      dim_foreground: "#CDD6F4" # text
      bright_foreground: "#CDD6F4" # text

    # Cursor colors
    cursor:
      text: "#1E1E2E" # base
      cursor: "#F5E0DC" # rosewater
    vi_mode_cursor:
      text: "#1E1E2E" # base
      cursor: "#B4BEFE" # lavender

    # Search colors
    search:
      matches:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0
      focused_match:
        foreground: "#1E1E2E" # base
        background: "#A6E3A1" # green
      footer_bar:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#1E1E2E" # base
        background: "#F9E2AF" # yellow
      end:
        foreground: "#1E1E2E" # base
        background: "#A6ADC8" # subtext0

    # Selection colors
    selection:
      text: "#1E1E2E" # base
      background: "#F5E0DC" # rosewater

    # Normal colors
    normal:
      black: "#45475A" # surface1
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#BAC2DE" # subtext1

    # Bright colors
    bright:
      black: "#585B70" # surface2
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#A6ADC8" # subtext0

    # Dim colors
    dim:
      black: "#45475A" # surface1
      red: "#F38BA8" # red
      green: "#A6E3A1" # green
      yellow: "#F9E2AF" # yellow
      blue: "#89B4FA" # blue
      magenta: "#F5C2E7" # pink
      cyan: "#94E2D5" # teal
      white: "#BAC2DE" # subtext1

    indexed_colors:
      - { index: 16, color: "#FAB387" }
      - { index: 17, color: "#F5E0DC" }
  gruvbox: &gruvbox
    primary:
      background: &gruvbox_dark_bg "#282828"
      foreground: "#ebdbb2"
      bright_foreground: "#fbf1c7"
      dim_foreground: "#a89984"
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    # search:
    #   matches:
    #     foreground: '#000000'
    #     background: '#ffffff'
    #   focused_match:
    #    foreground: CellBackground
    #    background: CellForeground
    #   bar:
    #     background: ''
    #     foreground: ''
    # line_indicator:
    #   foreground: None
    #   background: None
    selection:
      text: CellBackground
      background: CellForeground
    bright:
      black: "#928374"
      red: "#fb4934"
      green: "#b8bb26"
      yellow: "#fabd2f"
      blue: "#83a598"
      magenta: "#d3869b"
      cyan: "#8ec07c"
      white: "#ebdbb2"
    normal:
      black: *gruvbox_dark_bg
      red: "#cc241d"
      green: "#98971a"
      yellow: "#d79921"
      blue: "#458588"
      magenta: "#b16286"
      cyan: "#689d6a"
      white: "#a89984"
    dim:
      black: "#32302f"
      red: "#9d0006"
      green: "#79740e"
      yellow: "#b57614"
      blue: "#076678"
      magenta: "#8f3f71"
      cyan: "#427b58"
      white: "#928374"
  doom-one: &doom-one
    primary:
      background: "0x282c34"
      foreground: "0xbbc2cf"
    normal:
      black: "0x282c34"
      red: "0xff6c6b"
      green: "0x98be65"
      yellow: "0xecbe7b"
      blue: "0x51afef"
      magenta: "0xc678dd"
      cyan: "0x46d9ff"
      white: "0xbbc2cf"
  nightofx: &nightfox
    primary:
      background: "0x192330"
      foreground: "0xcdcecf"
    normal:
      black: "0x393b44"
      red: "0xc94f6d"
      green: "0x81b29a"
      yellow: "0xdbc074"
      blue: "0x719cd6"
      magenta: "0x9d79d6"
      cyan: "0x63cdcf"
      white: "0xdfdfe0"
    bright:
      black: "0x575860"
      red: "0xd16983"
      green: "0x8ebaa4"
      yellow: "0xe0c989"
      blue: "0x86abdc"
      magenta: "0xbaa1e2"
      cyan: "0x7ad4d6"
      white: "0xe4e4e5"
    indexed_colors:
      - { index: 16, color: "0xf4a261" }
      - { index: 17, color: "0xd67ad2" }

colors: *mocha
